const Routes = {
    Splash: 'Splash',
    Main: 'Main',
    SignIn: 'SignIn',
    SignUp: 'SignUp',
    ForgotPassword: 'ForgotPassword',
    VerifyPasswordScreen: 'VerifyPasswordScreen',
    Home: 'Home',
    Downloads: 'Downloads',
    Browse: 'Browse',
    Search: 'Search',
    ListTutors: 'ListTutors',
    TutorDetail: 'TutorDetail',
    Profile: 'Profile',
    Settings: 'Settings',
    SearchAll: 'SearchAll',
    SearchTutors: 'SearchTutors',
    SearchPaths: 'SearchPaths',
    SearchAuthors: 'SearchAuthors',
    SkillsDetail: 'SkillsDetail',
    ListTutorsByTypeScreen: 'ListTutorsByTypeScreen',
    AllPathsScreen: 'AllPathsScreen',
    TutorContent: 'TutorContent',
    TutorTranscript: 'TutorTranscript',
    SendFeedbackScreen: 'SendFeedbackScreen',
    AuthorScreen: 'AuthorScreen',
    NewReleasesScreen: 'NewReleasesScreen',
    PathScreen: 'PathScreen',
    Favourites: 'Favourites',
    CategoryDetailScreen: 'CategoryDetailScreen',
    RecommendedForYouScreen: 'RecommendedForYouScreen',
    MeScreen: 'MeScreen',
    MyTutorsTab: 'MyTutorsTab',
    EditProfileScreen: 'EditProfileScreen',
    ChangePasswordScreen: 'ChangePasswordScreen',
    TutorRatingTab: 'TutorRatingTab',
    TutorAssignmentTab: 'TutorAssignmentTab'
}

export default Routes